version: '3.8'

services:
  app:
    image: 'sast-checkmarx:latest'
    build:
      context: .
      target: release_img
    container_name: app_checkmarx
    environment:
      - INPUT_PATH=/usr/src/app/input
      - OUTPUT_PATH=/usr/src/app/output
    volumes:
      - ./input:/usr/src/app/input
      - ./output:/usr/src/app/output
